### PR TITLE
Include descriptions for builtin objects

### LINKED ISSUE #4: Include descriptions for builtin objects
Talon has a number of builtin objects, mostly actions, which come with their own documentation. Since talondoc runs outside of Talon, it doesn't have access to this documentation, so `TalonScriptDescriber.describe` fails when it encounters a builtin action, see [talondoc/util/describer.py#L104-L126][describe].

We should write a script which extracts this information to a versioned `.json` file, and add the contents of this file to the registry when talondoc loads.

An easy way to access this information is to capture the output of running `actions.list()` in ` ~/.talon/bin/repl`.

[describe]: https://github.com/wenkokke/talondoc/blob/d1d68b3844cacb825484fb6a8740c33b44ed3da4/talondoc/util/describer.py#L104-L126

### PR DESCRIPTION
**Pull request by Nova38**
Fixes #4

I added the script in a new preprocessing folder. If that is not the best place for it then we can move it. I tried to put it in the util folder but got some python importing of a partially initialized library errors. Currently the script will export the dictionary of the actions and their descriptions to a json file that includes the current talon version b`talon_actions_dict0.3.1-17-geb94.json`. There is the functionality to also extract the python function signatures, but I am not sure on how best to export them at the moment

### CODE REVIEW

**Comment by wenkokke** [comment]
It might make sense to expose this via the talondoc CLI.

**Comment by Nova38** [comment]
Good idea, I will move the functionality there

**Comment by wenkokke** [comment]
> Good idea, I will move the functionality there

Please define the function in the module that you have already created, and only use it in the `talondoc/__init__.py` file. That file should contain absolutely no logic.

**Comment by Nova38** [comment]
Ah okay will do

**Comment by Nova38** [comment]
Should i be exposing it via a second click cli command, and if so would a similar name like preprocess to that i used for the module be a good name for it? I am not entirely sure if preprocessing/preprocess is the best name for it, so if you have any better names i am open to changing it. I plan on finishing up the AST extraction stuff this Thursday biased on our discussion on slack. 

```
@cli.command(name="preprocess")
@click.argument(
    "output-dir",
    type=click.Path(),
)
```

**Comment by wenkokke** [comment]
> Should i be exposing it via a second click cli command, and if so would a similar name like preprocess to that i used for the module be a good name for it? I am not entirely sure if preprocessing/preprocess is the best name for it, so if you have any better names i am open to changing it. I plan on finishing up the AST extraction stuff this Thursday biased on our discussion on slack.
> 
> ```python
> @cli.command(name="preprocess")
> @click.argument(
>     "output-dir",
>     type=click.Path(),
> )
> ```

This seems fine, yeah! I'm not 💯 sold on "preprocess", but it works for now.

**Comment by wenkokke** [comment]
Merged via #41. (Sorry, couldn’t merge `main` into your branch.)

**Pull request closed without merging**
